// <auto-generated />
using System;
using LegendaryBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegendaryBot.Migrations
{
    [DbContext(typeof(LegendaryDbContext))]
    [Migration("20220612133716_change-path")]
    partial class changepath
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("LegendaryBot.Entities.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("LegendaryBot.Entities.MessageReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reaction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId1");

                    b.ToTable("MessageReactions");
                });

            modelBuilder.Entity("LegendaryBot.Entities.MessageResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId1");

                    b.ToTable("MessageResponses");
                });

            modelBuilder.Entity("LegendaryBot.Entities.MessageReaction", b =>
                {
                    b.HasOne("LegendaryBot.Entities.Guild", "Guild")
                        .WithMany("MessageReactions")
                        .HasForeignKey("GuildId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("LegendaryBot.Entities.MessageResponse", b =>
                {
                    b.HasOne("LegendaryBot.Entities.Guild", "Guild")
                        .WithMany("MessageResponses")
                        .HasForeignKey("GuildId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("LegendaryBot.Entities.Guild", b =>
                {
                    b.Navigation("MessageReactions");

                    b.Navigation("MessageResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
